project:
  type: website

website:
  title: "AAI1001 Lab Exercise 4"
  navbar:
    left:
      - href: index.qmd
        text: Table Data
      - href: singleTableQueries.qmd
        text: Single Table Queries
      - href: joiningTableQueries.qmd
        text: Joining Table Queries

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    paginate: false
    
execute:
  echo: false

editor: visual

